[package]
name = "oxidiser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.0"
magic-crypt = "3.1.12"
lz4_flex = { version = "0.9.3", default-features = false }